### PR TITLE
Support postgres hstore/jsonb fields #58

### PR DESCRIPTION
**Pull request by mrkamel**

### CODE REVIEW

**Comment by westonganger** [comment]
Is it time for this functionality to be merged into master?

**Comment by mrkamel** [comment]
@westonganger I wanted to to look into adding json support for mysql first as well. That's why it's not yet merged. Sorry for the delay.

**Comment by mrkamel** [comment]
Additionally, i thought about the neccessity to query deep json attributes, such that i wasn't 100% confident about the feature.

**Comment by mrkamel** [comment]
... added support for nested json via `column->nested->field`. Still thinking about json arrays and numbers. Currently, arrays are not supported and field data is expected to be strings.

**Pull request merged**
